### ISSUE TITLE
`channel-id` should also be honored when using an incoming webhook

### ISSUE THREAD

**Issue by grollinger** [slackapi/slack-github-action#101]
### Description

A Slack incoming webhook specifies a channel to post to, by default. But it is possible to override that for every message sent. The [slatify action](https://github.com/marketplace/actions/slatify), for example allows the user to override the default channel when using an incoming webhook.

This action does not do that. 

I would expect that if I specify a `channel-id`, it will be honored regardless of whether I'm using an app token or an incoming webhook.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
Hi @grollinger, overriding the channel to post in Incoming Webhooks is only available with [the legacy custom integration one](https://slack.com/apps/A0F7XDUAZ-incoming-webhooks) plus we don't generally recommend using it for new integrations. Please consider using the Incoming Webhooks as part of a Slack app instead. With the new way, the channel ID parameter no longer works.

**Comment by grollinger** [comment]
@seratch Thank you for the quick reply. We rely pretty heavily on the flexibility we get from choosing the destination channel dynamically. 

Do I understand correctly that "using the Incoming Webhooks as part of a Slack app" would mean that we would have to create one app per destination channel?

**Comment by seratch** [comment]
@grollinger 
>we would have to create one app per destination channel?

No, you can use a single Slack app for it. If you want to create three webhook URLs, you need to install the app three times.
