### ISSUE TITLE
Discussion about inactive 3rd party dependency projects

### ISSUE THREAD

**Issue by flaxel** [slackapi/slack-github-action#111]
### Description

I would suggest to remove the following libraries because they are not maintained since some years.

- [flat](https://github.com/hughsk/flat)
- [markup-js](https://github.com/adammark/Markup.js/)

### What type of issue is this? 
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [x] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
Ho @flaxel, thanks for writing in.

Indeed, these projects are not so active recently. However, they are used for this package's features. Refer to https://github.com/slackapi/slack-github-action/pull/71 for more details. As long as they work well for us, I don't think replacing them with other packages is an urgent task.

If we see any functionality/security issues with those packages in the future, we may consider stop using them. If you have any suggestions about the good alternative packages, sharing the information with us would be greatly appreciated.
