### ISSUE TITLE
To be able to include a multiple line Github Commit Message in a payload. Currently gives an error: Need to provide valid JSON Payload

### ISSUE THREAD

**Issue by brett-james-rocketlab** [slackapi/slack-github-action#116]
### Description

I'm unable to use the Payload if I use a multiple line or otherwise JSON Breaking string. I would like to include a git commit message in an action ( for example ${{ github.event.head_commit.message }} ), but it will break with new lines or formatting in there.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version: 1.21.0

node version: 14

OS version(s): MacOS 12.5

#### Steps to reproduce:

1. Create an action that uses a multiple line output, using the readme.md example:
`- name: Post to a Slack channel
  id: slack
  uses: slackapi/slack-github-action@v1.21.0
  with:
    # Slack channel id, channel name, or user id to post message.
    # See also: https://api.slack.com/methods/chat.postMessage#channels
    channel-id: 'CHANNEL_ID'
    # For posting a simple plain text message
    slack-message: "Git commit example: ${{github.event.head_commit.message }}\n it will be broken after here in the shell output"
  env:
    SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}`

2. The output in the shell will look off. In the blocks example, I have this:
```
 {
        "type": "section",
        "fields": [
          {
            "type": "mrkdwn",
            "text": "*Type:*\nAndroid 🤖"
          },
          {
            "type": "mrkdwn",
            "text": "*Build place:*\nBretts-MBP"
          }
        ]
      },
      {
        "type": "section",
        "text": {
          "type": "mrkdwn",
          "text": "*About this build*:\nCommit header
  
  This is a multiple line 
  commit message
  that might have some nice formatting?"
        }
      },
```

3. The error will be: `Error: Error: Need to provide valid JSON payload
`

#### Expected result:

What you expected to happen.
To be able to somehow put a commit message in the payload and show it to the user when posting a slack message.

#### Actual result:

What actually happened
Error: Error: Need to provide valid JSON payload

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by brett-james-rocketlab** [comment]
For what it's worth, I think I found it :) 

`                    "type": "mrkdwn",
                    "text": ${{ toJSON(github.event.head_commit.message) }}
                  }`

See the toJSON wrapper. because toJSON includes a double quote, you need to not have anything else in the text in that example. This will add \n for new lines, and make it otherwise sanitise for being in a JSON.

Happy days!

**Comment by seratch** [comment]
Glad to hear that you've figured out your way to deal with the pattern! Just for your reference, here is a similar issue discussed in the past. You can find a a bit different way to make the whole JSON data valid. https://github.com/slackapi/slack-github-action/issues/82

Let me close this issue now 👋
