### ISSUE TITLE
Support multiple channel IDs

### ISSUE THREAD

**Issue by glenthomas** [slackapi/slack-github-action#118]
### Description

The `channel-id` input supports a single channel ID. Can this be updated to support multiple comma-separated channel ID's?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by filmaj** [comment]
FYI this has been released in v1.22. Big ups to @treemmett for implementing, adding tests and updating the docs ❤️ .

**Comment by amirkarimi** [comment]
Thanks! What about [message updates](https://github.com/slackapi/slack-github-action?tab=readme-ov-file#update-the-message). How does it work in this case? I tried passing multiple channels and then updating the messages with the same returned `ts` but I got this error: `Error: An API error occurred: message_not_found`.
