### ISSUE TITLE
When updating a message it seems that Channel Name might not be allowed

### ISSUE THREAD

**Issue by mjaggard** [slackapi/slack-github-action#137]
### Description

When updating a message it seems that Channel Name might not be allowed

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [x] documentation related
- [x] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version: 

node version: 16

OS version(s): Ubuntu 22.04

#### Steps to reproduce:

1. Follow the instuctions here https://github.com/slackapi/slack-github-action#update-the-message
2. Use a Channel Name

#### Expected result:

The message should be updated and the task should succeed

#### Actual result:

The "started" message is posted fine but the success and failure messages do not appear in Slack and the GitHub Action fails with
> Error: An API error occurred: channel_not_found

**Comment by seratch** [comment]
Hi @mjaggard, thanks for writing in! 

We know this could be confusing but the underlying API for updating a channel message does not accept a channel name unlike the API to post a new message. Please use a channel ID instead. See also: https://github.com/slackapi/slack-github-action/issues/136#issuecomment-1271674074

**Comment by mjaggard** [comment]
Yes, understood thanks. I consider this to be an example / documentation bug.

The documentation for the channel ID field currently says you can use channel name which is only true in some circumstances. The example of an update could also make it clearer that the field has to contain and ID and not a name.

**Comment by seratch** [comment]
@mjaggard Thanks for the feedback. I just updated the README to be clearer: https://github.com/slackapi/slack-github-action/commit/0ae8044e6f4bda8d748e93c8d8fbc1d4a3b63f39 

Let us close this issue now. We're sorry for the confusion that you had.

**Comment by mjaggard** [comment]
That's awesome, thank you 😁
