### ISSUE TITLE
Upgrade to Node.js 16

### ISSUE THREAD

**Issue by Kurt-von-Laven** [slackapi/slack-github-action#138]
### Description

This repository uses Node.js 12 actions, which are deprecated. GitHub Actions recently began adding the following annotation warning all users of slackapi/slack-github-action:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: slackapi/slack-github-action

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
@tanguy-platsec Ah yes! You're right. The next version will come soon! Fixed by #128
