### ISSUE TITLE
GitHub Actions: Deprecating set-output commands

### ISSUE THREAD

**Issue by Nergie** [slackapi/slack-github-action#141]
### Description

This repository uses the command `set-output`, which is deprecated. GitHub Actions recently began adding the following annotation warning all users of slackapi/slack-github-action:
> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

You should replace all command `set-output` (`core.setOutput`) with the`GITHUB_OUTPUT` environment variable (`core.exportVariable`)

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by Nergie** [comment]
I no longer get annotation warnings. Using [@actions/core 1.10.0 ](https://github.com/slackapi/slack-github-action/blob/0591a83d97c714275147191f3660dde09458554e/package.json#L33) seems to solve the issue.

**Comment by aprettyloner** [comment]
Still experiencing this with `uses: slackapi/slack-github-action@v1.23.0`
