### ISSUE TITLE
Cannot get the test array's browser or projectName to consistently populate when test.describe() is used

### ISSUE THREAD

**Issue by john-cyndx** [slackapi/slack-github-action#143]
### Description

summaryResults.tests[i].browser and summaryResults.tests[i].projectName are only populated when the suiteName for a test is the path of the test. when test.describe() is used and the suiteName is given, the browser and projectName are empty strings.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version: 1.23.0

node version: 16.x

OS version(s): n/a

#### Steps to reproduce:

1. A test with the line test.describe('[some test suite title]')
2. Run the test on any browser or project
3. Browser and projectName will be blank for that test

#### Expected result:

Browser and projectName to be populated

#### Actual result:

Browser and projectName are empty strings in the test array object

**Comment by zimeg** [comment]
👋 I'm not sure if this still applies to the project in its current state, so going to close it. Please feel free to reopen or create a new issue whenever though!
