### ISSUE TITLE
Support custom variable interpolation in payload JSON file

### ISSUE THREAD

**Issue by adaminglehart** [slackapi/slack-github-action#150]
### Description

With the current implementation, it seems like the only variables that can be interpolated into the message payload are the ones from the [github context object](https://github.com/actions/toolkit/blob/main/packages/github/src/context.ts). It'd be really helpful to be able to pass in custom variables besides just what's available in there. Ideally you'd be able to just use anything in the `env` object but it doesn't seem like the github actions SDK allows you to access that? In that case I'd propose allowing something like a `vars` input that, if provided, will be accessible in your payload. Something like:

action.yml
```
env:
  myCustomVar: abc123

...

- name: Post slack message
  id: slack
  uses: slackapi/slack-github-action@v1.23.0
  with:
    channel-id: ${{env.channel_id}}
    payload-file-path: "./my-payload.json"
    vars: |
      {
        myVar: ${{env.myCustomVar}},
        application: Backend
      } 
```

my-payload.json
```
{
  "text": "{{{vars.application}}} deploy - {{vars.myvar}}"
}

```

I'm happy to take a pass at the implementation but wanted to verify that this would be of interest first

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
Hi @adaminglehart, thanks for sharing the suggestions. Our team will look into it sometime soon. If anyone has ideas or thoughts on this, please share them by posting comments here 👋

**Comment by seratch** [comment]
@adaminglehart Thanks for the reminder. Some members in our team are interested in this enhancement! 

I myself have a little hesitation to introduce a custom mechanism in addition to GitHub Actions platform features. My concern here is that our own feature addition may become a technical debt in the future when GH Actions adds something similar. Also, I am wondering if the implementation can be simple and easy to maintain in the long run. 

If you have already implemented something similar in the past, could you share the code with us first? With that, we may be more confident on this enhancement.

**Comment by HV-JRC** [comment]
Would this PR cover this case?

https://github.com/slackapi/slack-github-action/pull/159

**Comment by filmaj** [comment]
We tackled this issue in #200.
