### ISSUE TITLE
[Question] - Using BOT_TOKEN when rotation in app is enabled

### ISSUE THREAD

**Issue by ismaelflorit** [slackapi/slack-github-action#151]
### Description

App with token rotation - is use possible?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---
Hi there!

I was wondering if it's possible to use a bot token if token rotation is enabled for an app?

**Comment by e-zim** [comment]
Hi @ismaelflorit! As long as the bot token used by your action remains fresh, everything should work as expected!

I'm not sure how you're using this token outside of your action, but if you're only using it for the action you might consider using another GitHub Action that [runs on a schedule](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule) to [exchange and refresh your token](https://api.slack.com/authentication/rotation#exchange), then [updates the `BOT_TOKEN` secret in your repository](https://docs.github.com/en/rest/actions/secrets#create-or-update-a-repository-secret) to rotate this token from the same repo as your action.

**Comment by ismaelflorit** [comment]
Nice - hadn't thought of that flow!

Thanks :)
