### ISSUE TITLE
Triggering the action based on the Label on the Issue

### ISSUE THREAD

**Issue by meolivar** [slackapi/slack-github-action#158]
### Description

I am looking for a solution where the github action can only be triggered based on the label associated to the issue created in Github. 

The use case is we are trying to trigger the workflow to send a message to slack based on a specific label attached to the issue. 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version:

node version:

OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by srajiang** [comment]
Hi @meolivar,

It sounds like you might want to try configuring this workflow action to be triggered by the `issues` event payload with the activity type `labeled`. Github docs[ on that here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issues) are very helpful and contain some setup configuration which you can add to your workflow. 

```yml
on: 
   issues: 
       types: [labeled, unlabeled]
```

**Comment by zimeg** [comment]
👋 An [example workflow showcasing this](https://github.com/slackapi/slack-github-action/blob/main/example-workflows/Technique_2_Slack_API_Method/invite.yml) and a few more steps with `slackapi/slack-github-action@v2` is now included!
