### ISSUE TITLE
automate releases

### ISSUE THREAD

**Issue by stevengill** [slackapi/slack-github-action#16]
### Description

See https://partner.github.com/integration-resources/2021/03/19/pattern-releasing-and-maintaining-actions.html

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] enhancement (feature request)

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by robzr** [comment]
Submitted https://github.com/slackapi/slack-github-action/pull/23 to implement Steven's suggestion.

**Comment by stevengill** [comment]
Merged! Thanks @robzr!  let me know if v1.16.0 looks good

**Comment by robzr** [comment]
Hey @stevengill this is fantastic; works like a charm.  Thanks for the quick merge!  I like that it adds the `v1` and `v1.16` major / major.minor tracking tags too, so we don't have to pin to a patch.  👍 Gonna re-use this action for other stuff...
