### ISSUE TITLE
Send message even when Github Action fails

### ISSUE THREAD

**Issue by fnando** [slackapi/slack-github-action#179]
### Description

I noticed that no message is sent whenever the action fails to execute (see the image below). Is there a way to force the message for any action state? There are cases when error is as important as success (e.g. failing to build the app and deploying it).

Fwiw, I'm using the Slack Workflow Builder approach.

<img width="413" alt="CleanShot 2023-02-02 at 14 26 57@2x" src="https://user-images.githubusercontent.com/3009/216463664-325c1e28-7027-4540-838a-ab227f315a35.png">

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version:

node version:

OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by e-zim** [comment]
Hey @fnando, this is a pretty neat use case! It seems like this might be possible by adding `if: ${{ always() }}` to this step of your GitHub Action. An example with `failure()` can be found [on these docs](https://docs.github.com/en/actions/learn-github-actions/expressions#always), but the same syntax should apply to `always()`. I hope this is helpful!
