### ISSUE TITLE
Allow step users to pass any json payload to botToken to leverage blocks

### ISSUE THREAD

**Issue by thatrandybrown** [slackapi/slack-github-action#18]
### Description

Currently, the botToken portion of this action takes a message and sends it to slack as text, while the webhook allows any valid JSON to be sent to slack. Providing the ability to send json to both action types allows developers to pass in any valid JSON payload to be sent to slack, which will allow them to leverage `blocks` within their bot or app.

I'd be happy to work this enhancement.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
Hi @thatrandybrown, thanks for writing in!

I've checked your diff and introducing a new key `payload` this way looks great to me 👍 Could you submit a pull request if you have a chance?

**Comment by thatrandybrown** [comment]
@seratch thanks for following up! I've submitted the PR #22 :)
