### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by justin-newman** [slackapi/slack-github-action#180]
### Description

The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

This is just a warning really for now, but soon enough it will cause the action to fail. I'm sure the update can be lumped in with pretty much any other update that needs to happen.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version:
All
node version:
N/A
OS version(s):
N/A
#### Steps to reproduce:

1. Run the action successfully

#### Expected result:

The warning should not be there.

#### Actual result:

The warning was there.

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by seratch** [comment]
Hi @justin-newman, thanks for writing in! 

Our understanding is that upgrading `@actions/core` to 1.10+ should resolve this issue. Refer to https://github.com/slackapi/slack-github-action/pull/142#issuecomment-1296815092 for more details.

**Comment by bombillazo** [comment]
How does one "upgrade @actions/core"? I'm using the `slack-github-action` so not sure how one upgrade this

**Comment by justin-newman** [comment]
> How does one "upgrade @actions/core"? I'm using the `slack-github-action` so not sure how one upgrade this

We don't do anything, it looks like the necessary changes have already been made in the repo, we just need to wait for the next version of the action to be released and then it will be upgraded.

**Comment by hodigabi** [comment]
[The latest version](https://github.com/slackapi/slack-github-action/releases/tag/v1.23.0) resolve this warning, doesn't it?
