### ISSUE TITLE
Error: An API error occurred: not_in_channel

### ISSUE THREAD

**Issue by vitalyk-multinarity** [slackapi/slack-github-action#186]
### Description

I'm using this action in a few workflows. But when I tried to send to two channels, received "Error: An API error occurred: not_in_channel" error.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version:
slackapi/slack-github-action@v1

OS version(s):
Self-hosted, Debian 10
#### Steps to reproduce:

```
- name: Post to a Slack channel
        uses: slackapi/slack-github-action@v1
        with:
          channel-id: 'automation,testchannel'
          slack-message: |
            Processed zipfiles: 
            ${{ env.MESSAGE }}
```
#### Expected result:

Action should send message to both channels

#### Actual result:

"Error: An API error occurred: not_in_channel"

#### Attachments:
![Screenshot 2023-03-13 at 17 32 18](https://user-images.githubusercontent.com/97117484/224749893-0c30ee3c-824e-4ca7-8bcb-acbf0a6ed0ef.png)

  screenshot

**Comment by mwbrooks** [comment]
Hi @vitalyk-multinarity 👋🏻 Thanks for trying out the Slack GitHub Action!

Depending on the channel type, your [Slack bot must be a member of the channel](https://api.slack.com/bot-users#installing-bot) to send a message in the channel. This is for security reasons and often involves private channels, group DMs, and Slack Connect channels.

The solution is to [invite your Slack bot to the channel](https://slack.com/help/articles/201980108-Add-people-to-a-channel). Just have someone in the channel type `/invite @your-bot-name` or use the Slack UI to add the bot.

Please let me know if that helps!

**Comment by vitalyk-multinarity** [comment]
@mwbrooks - many thanks again, it works!

**Comment by FranciscoKloganB** [comment]
Sorry for posting a comment on a closed issue, however, I obtained my `SLACK_BOT_TOKEN` from a `GitHub` app and invited `GitHub` to the proper channel (public) using `/invite @github`, and I still get this error.

The bot as already appeared in the chat, but the action still fails

**Comment by vitalyk-multinarity** [comment]
> Sorry for posting a comment on a closed issue, however, I obtained my `SLACK_BOT_TOKEN` from a `GitHub` app and invited `GitHub` to the proper channel (public) using `/invite @github`, and I still get this error.
> 
> The bot as already appeared in the chat, but the action still fails. I have double checked the channel IDs. As you may see from the screenshot, the GitHub secret is also set. Any ideas on how I can further debug this? :(
> 
> ![image](https://user-images.githubusercontent.com/25959244/272225782-2680499f-02aa-4570-a3b5-ee184c1b31d9.png)
> 
> The channel ID belongs to `#alerts-prod-error-dp`. As we can see in the screenshot below.
> 
> <img alt="image" width="487" src="https://user-images.githubusercontent.com/25959244/272226648-4849cf7d-0128-4f8f-88b1-cd0cb15a541e.png">
> We can also confirm the `GitHub bot user` is in the channel with this other screenshot.
> 
> ![image](https://user-images.githubusercontent.com/25959244/272226187-1b1a2027-32c6-4176-a650-b5733e1f9220.png)
> 
> I also know that the bot has the required permissions to send messages, particularly `chat send` or `chat write` can't remember the name exactly, but the scope is granted.
> 
> ![image](https://user-images.githubusercontent.com/25959244/272227248-cdef24a8-e20c-4c22-8df3-e6cebb31ca8e.png)

Are you sure that your bot name is 'github'? In my channel, I see "/invite @GitHubNotifier" command, but I don't remember where/how we customize bot name.
