### ISSUE TITLE
Support thread_ts for threaded updates to a single topic

### ISSUE THREAD

**Issue by nsandary** [slackapi/slack-github-action#187]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [x] documentation related
- [x] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

I would like the ability to gather updates from a long build+deploy process into a single thread. I'd love to use this (or a similar) pre-built action to accomplish this, but I don't see any support (input parameter?) for `thread_ts`. I know the Slack API supports that functionality; is it possible to extend this GitHub Action to leverage that feature?

**Comment by nsandary** [comment]
Sorry, I did an additional search for `closed` topics and I see this has been discussed before.

[e.g. #75 #119]

**Comment by WilliamBergamin** [comment]
Hi @nsandary thanks for writing in!

Good point, adding documentation for this would be good 👍

**Comment by kalverra** [comment]
Seconded. It took me a while to figure this out after going through official docs. I also imagine it's a common enough use case where making `thread_ts` a standard input would also be handy.

**Comment by nsandary** [comment]
Just wanted to circle back and say thank you for completing this @WilliamBergamin! Very helpful! :-)
