### ISSUE TITLE
Formatting issue via action

### ISSUE THREAD

**Issue by jackherizsmith** [slackapi/slack-github-action#192]
### Description

Formatting from string created during action is being ignored

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version: 1.23.0

node version: 

OS version(s): ubuntu-latest

#### Steps to reproduce:

1. send string with `mrkdwn` formatting via webhook like "- thing 1\n- thing 2"

#### Expected result:

What you expected to happen

formatted:
- thing 1
- thing 2

#### Actual result:

unformatted:

\- thing 1
\- thing 2

#### Attachments:

<img width="182" alt="Screenshot 2023-04-12 at 22 37 12" src="https://user-images.githubusercontent.com/58533031/231591496-e570432b-fdb5-425f-9f97-64f05a735f36.png">

**Comment by seratch** [comment]
Hi @jackherizsmith, unfortunately, Slack's mrkdwn does not natively support markdown's list sytanx. As a workaround, you need to `• item 1\n• item 2\n• item 3` or something like that. Also, we don't tell whether any enhancements regarding this can come in the future. I know the answer here is not great for you, but I hope this helps clarify.

**Comment by jackherizsmith** [comment]
That's very helpful clarification - so assuming the more advanced `<@U[SLACK_ID]>` also won't work?

**Comment by jackherizsmith** [comment]
is there an alternative you can recommend, in order to get this formatting to work?

**Comment by jackherizsmith** [comment]
I suppose rather than using this action, I could write a custom step that invokes [curl](https://api.slack.com/tutorials/tracks/posting-messages-with-curl)

**Comment by seratch** [comment]
The list syntax just does not exist. Any other syntax available [here](https://api.slack.com/reference/surfaces/formatting) should work when using this GitHub action library. Please refer to https://github.com/slackapi/slack-github-action/tree/main/example-workflows too.

**Comment by jackherizsmith** [comment]
ah I see interesting! so lists (bullet points) are specifically broken, and everything else should work as documented?

**Comment by ryan-williams** [comment]
I'm using [Technique 1: Slack Workflow Builder](https://github.com/slackapi/slack-github-action#technique-1-slack-workflow-builder) and not observing any formatting to work. That doc link says:
> You can select where you want to post the data and how you want to format it in Slack's workflow builder interface.

but the Workflow Builder modal doesn't let me do much with the "variables" (e.g. can't use them in links or code fences). It seems to let me bold-face or italicize a "variable":

![image](https://github.com/slackapi/slack-github-action/assets/465045/dac0e858-357d-4019-9057-e785d603d8aa)

but even that doesn't work; everything is rendered without formatting:

![slack gha post unformatted](https://github.com/slackapi/slack-github-action/assets/465045/e2c308a7-e6f0-404b-99f8-4bf2d1dc4a1f)

[Here's the GHA run](https://github.com/ryan-williams/slack-gha-test/actions/runs/5589424564/jobs/10217681880#step:2:4):

```yml
Run slackapi/slack-github-action@v1.24.0
  with:
    payload: {
    "text": "Sample text, *bold1* **bold2** _italic_ `code` [link](https://github.com/slackapi/slack-github-action)\n```code fence```\n"
  }
  
  env:
    SLACK_WEBHOOK_URL: ***
```


@seratch when you said:
> Any other syntax available [here](https://api.slack.com/reference/surfaces/formatting) should work when using this GitHub action library.

is that supposed to apply to "Technique 1"?

**Comment by seratch** [comment]
@ryan-williams 
>is that supposed to apply to "Technique 1"?

No, any of Slack syntax does not work in Workflow Builder variables. I should have been more specific, but I meant, as long as you use incoming webhooks or chat.postMessage API to directly post a Slack message from your GitHub Actions job, any formatting syntax are available for it while they are not available for Workflow Builder integration.

@jackherizsmith Sorry for my late response here:
>so lists (bullet points) are specifically broken, and everything else should work as documented?

All the syntax documented work as you expect.

Let me close this issue now 👋
