### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by karelbemelmans** [slackapi/slack-github-action#199]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

Can we get a new release? I would love to use the `channel_id` output that was added last year but has not made it into a new release yet.

**Comment by filmaj** [comment]
Release v1.24.0 is out!
