### ISSUE TITLE
What does the "Slack App Route" allow for?

### ISSUE THREAD

**Issue by josegonzalez** [slackapi/slack-github-action#20]
### Description

The documentation [here](https://github.com/slackapi/slack-github-action#slack-app-route) kinda tapers off. Can it be updated?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [x] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version: *

node version: *

OS version(s): *

#### Steps to reproduce:

1. Read the docs
2. ???
3. Actually there is no profit step 😃 

#### Expected result:

Me understanding the benefits of the Slack App Route.

#### Actual result:

Me asking what the benefits are in a GitHub issue.

#### Attachments:

This video of cats meowing always attracts my cat to it: https://www.youtube.com/watch?v=XgbkY3TkAHI

**Comment by seratch** [comment]
Thanks for taking the time to write in! I just sent a pull request to improve the part in README.
