### ISSUE TITLE
Proxy configuration is ignored when using bot token

### ISSUE THREAD

**Issue by raihle** [slackapi/slack-github-action#204]
### Description

This issue is similar to #131, but applies when using a bot instead of a webhook. When using the action behind a corporate proxy (e.g. on self-hosted runners), connection will time out because the proxy configuration is not respected.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Reproducible in:

package version: 1.24.0

node version: 16

OS version(s): Ubuntu 22.04

#### Steps to reproduce:

1. Set up a proxy for outgoing HTTPS traffic, and block all other outgoing HTTPS traffic
2. Point HTTPS_PROXY / https_proxy to the proxy
3. Run the action using bot token and channel ID

#### Expected result:

The message is sent

#### Actual result:

The actions fails due to connection timeout

#### Attachments:

```
Run slackapi/slack-github-action@v1.24.0
  with:
    channel-id: xxxxxxxxx
    slack-message: XXXXXXXXX
  env:
    SLACK_BOT_TOKEN: ***
[WARN]  web-api:WebClient:0 http request failed connect ETIMEDOUT xxx.xxx.xxx.xxx:443
[WARN]  web-api:WebClient:0 http request failed connect ETIMEDOUT yyy.yyy.yyy.yyy:443
[WARN]  web-api:WebClient:0 http request failed connect ETIMEDOUT yyy.yyy.yyy.yyy:443
[WARN]  web-api:WebClient:0 http request failed connect ETIMEDOUT zzz.zzz.zzz.zzz:443
[WARN]  web-api:WebClient:0 http request failed connect ETIMEDOUT www.www.www.www:443
[WARN]  web-api:WebClient:0 http request failed connect ETIMEDOUT yyy.yyy.yyy.yyy:443
[WARN]  web-api:WebClient:0 http request failed connect ETIMEDOUT yyy.yyy.yyy.yyy:443
[WARN]  web-api:WebClient:0 http request failed connect ETIMEDOUT www.www.www.www:443
[WARN]  web-api:WebClient:0 http request failed connect ETIMEDOUT yyy.yyy.yyy.yyy:443
[WARN]  web-api:WebClient:0 http request failed connect ETIMEDOUT xxx.xxx.xxx.xxx:443
[WARN]  web-api:WebClient:0 http request failed connect ETIMEDOUT www.www.www.www:443
Error: Error: A request error occurred: connect ETIMEDOUT yyy.yyy.yyy.yyy:443
```

----

@slack/web-api's WebClient already supports sending a custom `agent` (and intentionally disables Axios' proxy detection). I don't think this is a hard problem to fix, but I couldn't figure out how to write satisfactory tests for it.

**Comment by raihle** [comment]
Thanks @hello-ashleyintech!

Yes, I am sure that the environment variables are set. Actually, we were using an (old) fork of this repository until recently with the proxy functionality hacked in. I took some time to do that again (based on the current main) in #205. I managed to add some rudimentary tests as well, but I'm very open to suggestions.

**Comment by hello-ashleyintech** [comment]
@raihle Wonderful, thank you so much for opening that PR 🙌 I will take a look either later today or first thing tomorrow and will be sure to leave some feedback if needed 😄
