### ISSUE TITLE
Update app to be compatible with https-proxy-agent 7.0.0

### ISSUE THREAD

**Issue by hello-ashleyintech** [slackapi/slack-github-action#213]
### Description

Currently, the `https-proxy-agent` package is on v5.0.1. Dependabot opened a PR (https://github.com/slackapi/slack-github-action/pull/212) to bump this up two major versions to 7.0.0 - however, [this version bump fails the HTTP Proxy unit test that was added to the Slack Send unit tests](https://github.com/slackapi/slack-github-action/actions/runs/5145837771/jobs/9264036833?pr=212). It would be great to update this package to the most recent version for security purposes and also adjust the code's use of the package so that it's compatible with the latest version, 7.0.0, and the unit tests pass.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request) - dependency
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

**Comment by zimeg** [comment]
Thanks for tracking this, and thank you @dependabot! Closing with the fix in #241 🚀
