### ISSUE TITLE
Can't we attach a file along with text using this action

### ISSUE THREAD

**Issue by govindgupta1103** [slackapi/slack-github-action#215]
We are not authorized to use unverified Github marketplace products. Is it possible to send the uploaded artifact to slack using this? I am able to send text though

**Comment by srajiang** [comment]
@govindgupta1103 Hi Govind, unfortunately the ability to upload files to Slack is not supported through this Github Action at this time. Looks like we're tracking this as a feature request [here](https://github.com/slackapi/slack-github-action/issues/92), and its a popular request too! 👀  

Let me close this issue for now to avoid duplicates.

**Comment by govindgupta1103** [comment]
@srajiang  Is it possible to upload the file using Slack API which starts as CURL -F something? Please respond.
