### ISSUE TITLE
Payload file example for workflows webhooks does not work

### ISSUE THREAD

**Issue by jalaziz** [slackapi/slack-github-action#227]
### Description

The payload file example for Workflow Webhooks doesn't work. In particular, Workflows does't support advanced formatting.

This payload is not valid for Workflow-based Webhooks: https://github.com/slackapi/slack-github-action/blob/main/example-workflows/Technique_1_Slack_Workflow_Builder/payloads/example.json

Maybe Workflow Webhooks shouldn't be recommended as the default integration mechanism?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [x] documentation related
- [x] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

**Comment by seratch** [comment]
Hi @jalaziz, thanks for taking the time to report the issue. You're right, the example payload has been incorrect for a while. I've now updated the file to contain a more appropriate one.

>In regard to Workflow Webhooks being recommended as the default integration mechanism

This really depends on what a developer wants to achieve. If you want to pass attachments/blocks from the GitHub Action side, indeed, the Workflow Builder integration might not be the best choice. However, if you want to pass only variables and pieces of data to Slack and then construct the notification message in a following step on the Workflow Builder side, a rich message can be easily sent.

It's worth noting that Slack will soon release a new version of the Workflow Builder. The updated workflow engine will continue to support incoming webhooks to trigger a workflow. So there'll be no significant changes on this GH Action library side, but the configuration process might vary slightly. Once the new version is made available to everyone, this project needs to update the README and provide examples to help developers adapt.

Thank you again for your feedback. I've corrected the payload example and, as we have nothing further to share on this topic, let me close this issue for now.
