### ISSUE TITLE
How can I mark the whole block as RED to indicate failure?

### ISSUE THREAD

**Issue by zhaoyi0113** [slackapi/slack-github-action#247]
### Description

I am using webhook incoming message to send message to slack channel. It works fine but all the blocks shown in block has the same color. I'd like to make the block color different for passing and failure. Does it have any attribute I can use for that?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ x] enhancement (feature request)
- [x ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x ] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version:

node version:

OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by seratch** [comment]
Hi @zhaoyi0113, thanks for asking the question. When you place `blocks` inside an `attachment`, you can use a color bar for your message. Here is [an example](https://app.slack.com/block-kit-builder/#%7B%22attachments%22:%5B%7B%22color%22:%22#f2c744%22,%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22You%20can%20place%20any%20blocks%20here%22%7D%7D%5D%7D%5D%7D). I hope this helps.

**Comment by zhaoyi0113** [comment]
@seratch thanks for sharing it. It works. But can I put a condition on choosing which colour to use based on build status? 
If not, I will have to create two actions and add condition on that action

**Comment by seratch** [comment]
Block Kit itself does not provide such a funtionality, so you can use GitHub Actions' conditions for it. Since this is not Slack specific, you can find many answers on the internet like this: https://stackoverflow.com/questions/58858429/how-to-run-a-github-actions-step-even-if-the-previous-step-fails-while-still-f 

Having two `attachements` JSON data for success and failure in your workflow can be a little bit repetitive, though. Is everything clear now?

**Comment by zhaoyi0113** [comment]
that makes sense. Thanks
