### ISSUE TITLE
Enable emojis for slack-message input.

### ISSUE THREAD

**Issue by dabitk** [slackapi/slack-github-action#248]
### Description
Emojis in Slack messages are very frequently used.
We can implement this simple emoji support by passing {"type": "plain_text", "text": message, "emoji": true} as text parameter for `web.chat.update(...)` `web.chat.postMessage(...)` APIs.

Although I think by passing `block` properties as JSON payload we can achieve the same goal, I think it is much more intuitive for users of this Github Action if `slack-message` input supports emojis by default.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

**Comment by seratch** [comment]
Hi @dabitk, thanks for taking the time to share the suggestion! However, using `blocks` is the right way to use `plain_text` block elements, so we don't plan to add a different way to achieve the same. It'd be appreciated if you could understand this. Thanks again for your interest on the enhancement!
