### ISSUE TITLE
Error: no_service

### ISSUE THREAD

**Issue by humanendpoint** [slackapi/slack-github-action#249]
### Description

Trying to send a payload to a Slack webhook. While this used to work fine, now I get the below error when using `uses: slackapi/slack-github-action@v1.24.0` in a step. Clicking the action in VSCode leads to this repo, but with `This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.` as a banner on the page. Any way to bypass this?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version: v1.24.0

OS version(s): macos-latest

#### Steps to reproduce:

1. Add the action to an Actions step
2. Run it

#### Expected result:

The Action to run.

#### Actual result:
Error message:
```
axios post failed, double check the payload being sent includes the keys Slack expects
{
  text: 'text',
  blocks: [
    { type: 'header', text: [Object] },
    { type: 'section', text: [Object], accessory: [Object] },
    { type: 'context', elements: [Array] }
  ]
}
Error: no_service
Error: Request failed with status code 404
```

**Comment by seratch** [comment]
>Error: Request failed with status code 404

This indicates your webhook URL can be invalid or deleted for some reason. Anyone who has access to the incoming webhook configuration page can revoke the URL. Could you check if the URL is still active by sending a request using `curl` etc.?

**Comment by humanendpoint** [comment]
solved by switching to @main.

**Comment by pgangloff-hbs** [comment]
can you expand on the solution? I have the same problem/error. I  have this in my github action:
`  # Read this for slack setup: https://github.com/slackapi/slack-github-action
      - name: Slack notification/workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "status": "${{ job.status }}",
              "tag": "${{ steps.new-tag.outputs.new-tag-name }}",
              "message":"${{env.APP_ID}} deployed to dev with tag ${{ steps.new-tag.outputs.new-tag-name }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}`

And I've setup my secret in github. And I've created my workflow in slack, set up the three variables (status, tag, message). I copied the URL into the github secret... But I get this error:

`axios post failed, double check the payload being sent includes the keys Slack expects
{
  status: 'success',
  tag: '2.0.2.2023.12.13T203834',
  message: 'dre deployed to dev with tag 2.0.2.2023.12.13T203834'
}
Error: <!DOCTYPE html><html lang="en-US" class=""><head><script type="text/javascript" crossorigin="anonymous" src="[https://a.slack-]
...I truncated all the HTML returned with the 404...
`

**Comment by pgangloff-hbs** [comment]
> can you expand on the solution? I have the same problem/error. I have this in my github action: - name: Slack notification/workflow id: slack uses: slackapi/slack-github-action@v1.24.0 with: payload: | { "status": "${{ job.status }}", "tag": "${{ steps.new-tag.outputs.new-tag-name }}", "message":"${{env.APP_ID}} deployed to dev with tag ${{ steps.new-tag.outputs.new-tag-name }}" } env: SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
> 
> And I've setup my secret in github. And I've created my workflow in slack, set up the three variables (status, tag, message). I copied the URL into the github secret... But I get this error:
> 
> axios post failed, double check the payload being sent includes the keys Slack expects { status: 'success', tag: '2.0.2.2023.12.13T203834', message: 'dre deployed to dev with tag 2.0.2.2023.12.13T203834' } Error: <script type="text/javascript" crossorigin="anonymous" src="[https://a.slack-] ...I truncated all the HTML returned with the 404... Error: Request failed with status code 404

Ignore my previous message, I had copied the wrong slack URL. It needs to be the slack 'Web request URL', and not the slack 'Worflow link", doh!

**Comment by naoya7076** [comment]
Even after updating to the latest version 1.25.0, this issue occurs. Notifications are being sent to Slack, and there is no issue with the content of the messages. However, in the workflow, it displays `Error: no_service Error: Request failed with status code 404`.

**Comment by petern48** [comment]
> > Error: Request failed with status code 404
> 
> This indicates your webhook URL can be invalid or deleted for some reason. Anyone who has access to the incoming webhook configuration page can revoke the URL. Could you check if the URL is still active by sending a request using `curl` etc.?

@seratch Could you elaborate on how webhook URLs may become invalid? Our's silently started to fail, and we fixed it by creating a new one and replacing it. We didn't delete it, so it seemed to somehow expire. We'd like to know how we can make it more reliable.
