### ISSUE TITLE
Integration tests always fail for pull requests from a fork

### ISSUE THREAD

**Issue by zimeg** [slackapi/slack-github-action#251]
### Description

For PRs sent from a fork, the integration tests always fail since secrets for the action are not being shared. Example in #250.

From the "Actions" tab in settings:

> Anyone with collaborator access to this repository can use these secrets and variables for actions. They are not passed to workflows that are triggered by a pull request from a fork.

It looks like there's [a workaround](https://michaelheap.com/access-secrets-from-forks/) that requires some additions to the workflow file to use secrets on a re-run. I'm unsure of other solutions, but I think this approach seems alright!

### What type of issue is this?
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [x] testing related
- [x] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by WilliamBergamin** [comment]
@zimeg Will this approach ensure that a bad actor isn't able to print or scrape/send our secrets by opening a PR from a fork?

These secrets are restricted in out test Team but I don't think anyone wants to update them for no reason 😟

**Comment by WilliamBergamin** [comment]
It may also be possible to configure the [workflow approval requirements](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks) of this repository in order to require approval of the changes before executing the GitHub actions 💡

**Comment by zimeg** [comment]
@WilliamBergamin these might compliment each other well! I think even with approvals, "workflows from forks do not have access to sensitive data such as secrets" so we may want to use the workflow approval requirement to require an approval, then use this approach to share secrets (if all of the changes seem safe).
