### ISSUE TITLE
Update Existing Message Using Incoming Webhook

### ISSUE THREAD

**Issue by ShahroZafar** [slackapi/slack-github-action#252]
### Description

From what I understand you can only update an existing message with the Option 2 i.e. [Technique 2: Slack App](https://github.com/slackapi/slack-github-action#technique-2-slack-app). Is it possible to do the same with incoming webhook? If so how

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
Hi @ShahroZafar, thanks for asking the question! Unfortunately, it's not feasible to do the same with incoming webhooks.

**Comment by ShahroZafar** [comment]
Hi @seratch. Thanks for the reply.
I ended up using the Technique 2.
