### ISSUE TITLE
New release to support node20?

### ISSUE THREAD

**Issue by mattnakama-skytap** [slackapi/slack-github-action#278]
### Description

I have node v20 on my self-hosted action runner, but the latest release (v1.24.0) of slack-github-action requires node v18.

I tried to use `slackapi/slack-github-action@main`, but `dist/index.js` is missing. I ended up forking `main` and running `npm ci && npm run build` to make a node20 compatible version [here](https://github.com/mattnakama-skytap/slack-github-action/tree/node20), but it's not quite clean.

I don't quite understand the branching model that this repo uses to cut releases. Could a maintainer perhaps cut a 1.25.0 release from the main branch with official node20 support? Thanks.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Reproducible in: 1.24.0

package version: github-runner-2.311.0

node version: 20.9.0 (nodejs_20)

OS version(s): NixOS 23.11

#### Steps to reproduce:

1. Install and configure github action runner
2. Install NodeJS v20
3. Make a workflow that calls `slackapi/slack-github-action@v1.24.0`
4. Trigger the workflow

#### Expected result:

Workflow would use node20, or there would be a tagged release that uses node20

#### Actual result:

Failure running workflow when it tries to find node16. Latest v1.24.0 release only works on node16, and there is no way to select a git commit from the current `main` branch for node20 support.

**Comment by danielzohar** [comment]
GitHub actions now logs a warning when running actions using Node 16. This is the line for `slackapi/slack-github-action`

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: slackapi/slack-github-action@v1.24.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by aanderse** [comment]
this was resolved in #267, we just need a new release now

maybe @seratch, who merged #267, can help us initiate a new release :man_shrugging:

**Comment by JamesMGreene** [comment]
also cc @filmaj, who appears to be assigned to many of the tasks for the [`1.25` milestone](https://github.com/slackapi/slack-github-action/milestone/12).

**Comment by filmaj** [comment]
Here we go: https://github.com/slackapi/slack-github-action/releases/tag/v1.25.0

**Comment by acottre** [comment]
This was a breaking change, we've had to pin our version to v1.24 now as runners without node20 support will fail.

```
Download action repository 'slackapi/slack-github-action@v1' (SHA:6c661ce58804a1a20f6dc5fbee7f0381b469e001)
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node20' is not supported, use 'docker', 'node12' or 'node16' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load slackapi/slack-github-action/v1/action.yml
```
