### ISSUE TITLE
Choose Action icon and color

### ISSUE THREAD

**Issue by filmaj** [slackapi/slack-github-action#283]
Went to publish a new release and saw this UI:

<img width="948" alt="Screenshot 2024-01-26 at 4 46 36 PM" src="https://github.com/slackapi/slack-github-action/assets/52645/967b1ad3-da6a-40e7-955d-7b34de8f85a4">

**Comment by zimeg** [comment]
Stumbled into [some related docs](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding) while taking a look at `action.yml` - stinks that `slack` isn't allowed 😂

I wonder if we want to continue omitting these values? The [marketplace search](https://github.com/marketplace?query=slack) has a decent branding already IMO. Though the name of this action might be worth revisiting soon...


<img width="372" alt="marketplace" src="https://github.com/slackapi/slack-github-action/assets/18134219/923a0347-2d93-4ede-8628-0cc6d90ddd23">

**Comment by zimeg** [comment]
This was somewhat updated with some of the changes in `slackapi@slack-github-action@v2.0.0`! At least the name and description:

![action](https://github.com/user-attachments/assets/079306a7-9780-4e83-ba07-836688df2c13)

For now I think we can close this and keep the default icon, but I'm always open to revisiting later!
