### ISSUE TITLE
Pull Request notification so slack only sending the part of the JSON not the entire JSON file

### ISSUE THREAD

**Issue by JyotiPrakashMallick** [slackapi/slack-github-action#293]
### Description
 
 Designed an action in GitHub which will send slack notification when a PR raised,  my YAML file is 
 
```
---
name: Pull Request Notifier
on:
  pull_request:
    types:
      - opened
      - reopened
jobs:
  notify:
    name: PR notification
    runs-on: ubuntu-latest
    steps:
      - name: Post message
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/<secret>
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {  
               "text": "New pull request opened",
               "title": ${{ toJson(github.event.pull_request.title) }},
               "author": ${{ toJson(github.event.pull_request.user.login) }},
               "link": ${{ toJson(github.event.pull_request.html_url) }}
             }
```
 But when a PR is getting raised I am only seeing "New pull request opened" not the entire payload. But in the log I can see the entire payload 
 
 ```
Run slackapi/slack-github-action@v1.25.0
  with:
    payload: {  
     "text": "New pull request opened",
     "title": "Slack Test",
     "author": "PerfAdmin",
     "link": "https://<gitrepo>/pull/15"
   }
  
  env:
    SLACK_WEBHOOK_URL: https://hooks.slack.com/services/<secret>
    SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
```

Slack notification screenshot : 

![image](https://github.com/slackapi/slack-github-action/assets/6301012/1bc091e0-ff2d-40e1-b790-1e15fffe4c00)

What I am missing here ? 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x ] bug
- [ ] enhancement (feature request)
- [ x] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x ] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by zimeg** [comment]
Hey @JyotiPrakashMallick 👋  The `INCOMING_WEBHOOK` payload expects [an array of `blocks` for custom formatting](https://github.com/slackapi/slack-github-action?tab=readme-ov-file#usage-2) and will fallback to `text` like you're seeing here.

You could experiment with different layouts for the information in this payload using [Block Kit Builder](https://app.slack.com/block-kit-builder) or keep the same payload but setup a workflow in Workflow Builder and use a [`SLACK_WEBHOOK_URL`](https://github.com/slackapi/slack-github-action?tab=readme-ov-file#technique-1-slack-workflow-builder) instead.

I'm hoping one of these options is helpful, but please let me know if you're still not finding your payload appear!

**Comment by JyotiPrakashMallick** [comment]
@zimeg thank you for your response, yeah I have tried the `Block Kit Builder` and now it is working fine.

with:
          payload: |
            {
              "text": "New pull request opened",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*New pull request opened*\nTitle: ${{github.event.pull_request.title}}\nAuthor: ${{github.event.pull_request.user.login}}\nLink: ${{github.event.pull_request.html_url}}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/<secret>
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
