### ISSUE TITLE
Node.js 16 actions are deprecated.

### ISSUE THREAD

**Issue by orome** [slackapi/slack-github-action#298]
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: slackapi/slack-github-action@v1.24.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

**Comment by hello-ashleyintech** [comment]
hi, @orome! Thanks for your submission! 😄 

Based on the provided error message, it looks like you're using `v1.24.0`. I recommend upgrading to `v1.25.0`, which is the latest version and includes the version bump for Node 20 (see [release notes](https://github.com/slackapi/slack-github-action/releases/tag/v1.25.0)).

**Comment by orome** [comment]
@hello-ashleyintech OK I'll do another push. I thought I'd done just that but maybe there's something else going on.

**Comment by orome** [comment]
Yeah my mistake I misread the latest error, which just refers to [another action](https://github.com/tsickert/discord-webhook/issues/163).

**Comment by hello-ashleyintech** [comment]
Thanks for the update @orome! 😄 Since this issue looks to be resolved, I'll close it out, but please don't hesitate to open a new issue if something else comes up! 🙌
