### ISSUE TITLE
This action is available in the Github context, but it's the octkit context, not the Github Actions context, and I can't find any explanation for it anywhere.

### ISSUE THREAD

**Issue by mecaota** [slackapi/slack-github-action#347]
https://github.com/slackapi/slack-github-action/blob/2c861179a189d86abe184dc3c2e848a7bc6f791f/src/slack-send.js#L45

In this Actions, it is stated that the github context is available and that if payload json file is prepared, it will be parsed, but this is not the [github context of Github Actions](https://docs.github.com/ja/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context), but [the context provided by octokit](https://github.com/actions/toolkit/blob/main/packages/github/src/context.ts#L6). This is misleading due to insufficient explanation in the current documentation. Please state in the documentation that it is the octokit context.

Even if you write it according to the context described in the Github Actions documentation, it will be parsed as "???" because the octokit github context is different from the camel case and snake case, and the context itself provided is different.

I spent an hour trying to solve this. The documentation is very unhelpful.

**Comment by zimeg** [comment]
Hey @mecaota 👋   Thank you so much for reporting this!

These variables have caused a lot of confusion before, some of it in #226, and I appreciate you pointing to a cause for some missing variables 🙏 

The `octokit` context you shared is what I'm finding in the actual action, and wrapped within the `payload` is details for the [webhook event](https://docs.github.com/en/webhooks/webhook-events-and-payloads).

I'm sorry about the added confusion this caused - I'm thinking the similar `context` naming has been confusing before. We'll update this documentation soon 📚

**Comment by zimeg** [comment]
The [`README`](https://github.com/slackapi/slack-github-action/tree/main?tab=readme-ov-file#sending-variables) now references the different possibilities of these payloads 🚀 

 I think we can improve this with examples in follow up changes, but right now these are better details on payloads share IMO. Thank you again for sharing these links!
