### ISSUE TITLE
Typo in release note for v2.0.0: Incorrect webhook-type value

### ISSUE THREAD

**Issue by tsuchiya-yu** [slackapi/slack-github-action#356]
### Description

There is a typo in the release notes for version `v2.0.0`. 

In the section ["Technique 3: Slack incoming webhook"](https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0#the-webhook-type-must-be-specified-for-incoming-webhooks), the text mentions:

> Set the webhook-type value to `webhook-trigger`

The correct value should be:

> Set the webhook-type value to `incoming-webhook`

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [x] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version: Not applicable (documentation issue)

node version: Not applicable

OS version(s): Not applicable

#### Steps to reproduce:

1. Visit the [v2.0.0 release notes](https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0).
2. Scroll to the section titled ["Technique 3: Slack incoming webhook"].
3. Observe the incorrect value `webhook-trigger` mentioned as the `webhook-type` value.

#### Expected result:

The `webhook-type` value should be `incoming-webhook`.

#### Actual result:

The `webhook-type` value is incorrectly mentioned as `webhook-trigger`.

#### Attachments:

None.

**Comment by zimeg** [comment]
@tsuchiya-yu Thank you for catching this and sharing! 📝 ✨ 🙏 

These release notes are now updated! 🚀  I'm hoping more unexpected typos didn't slip in 😉
