### ISSUE TITLE
Coloured Bar for Block kit

### ISSUE THREAD

**Issue by ms3sm2** [slackapi/slack-github-action#364]
### Description

I can use coloured side bar in attachments but I don't find that option in block kit. I would like to add coloured bar in the below block kit. As of now we are getting only white coloured bar. Is there any way that we can add customized colour bar for the block kit ?

```json
{
	"blocks": [
		{
			"type": "rich_text",
			"elements": [
				{
					"type": "rich_text_quote",
					"elements": [
						{
							"type": "text",
							"text": "I am a basic rich text quote, \n\nI can have multiple paragraph breaks within the block."
						}
					]
				}
			]
		}
	]
}
```

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [ x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x ] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Expected result:

![image](https://github.com/user-attachments/assets/0af6ae5d-ea86-4389-9b2a-abd6e046a402)

#### Actual result:

![image](https://github.com/user-attachments/assets/bf4235e5-cebc-4fe9-a8d0-5bd95ce70727)

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by seratch** [comment]
Hi @ms3sm2, thanks for asking the question!

When you pass an attachment that includes blocks inside, you can display color bar within a posted message. 
```json
{
  "attachments": [
    {
      "color": "#f2c744",
      "blocks": [
        {
          "type": "section",
          "text": {
            "type": "plain_text",
            "text": "This is a plain text section block."
          }
        }
      ]
    }
  ]
}
```

You can use chat.postMessage to use attachments: https://github.com/slackapi/slack-github-action?tab=readme-ov-file#technique-2-slack-api-method

**Comment by ms3sm2** [comment]
Hi @seratch ,

I understand that Slack API attachments are deemed legacy and will be phased out shortly. Is this correct?

**Comment by seratch** [comment]
Attachments are indded no longer recommended for general rich message construction. That said, they won't be removed anytime soon since they are widely used by many apps worldwide. They may be phased out in the long run (say, in years), but there is no timeline for that as of today. Regarding this color bar use case, using blocks as an attachment is the only way to achieve this, so you can rely on it for now.
