### ISSUE TITLE
Support file as payload input

### ISSUE THREAD

**Issue by umbertix** [slackapi/slack-github-action#43]
### Description

It would be very nice if instead of having only the text payload option, the action could take a json file path input.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by srajiang** [comment]
Hi @umbertix - Marking this as an enhancement and adding this to consideration for future release. Thank you for the suggestion and for trying out our git action! 

Additionally, we welcome contributions from the community as well.
