### ISSUE TITLE
Fancy messages with Slack App Webhooks

### ISSUE THREAD

**Issue by YaroslavRepeta** [slackapi/slack-github-action#6]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

I wanted to use this GitHub Action with Slack App Webhooks rather than Slack Workflows.
So that I could send fancy messages (built in https://app.slack.com/block-kit-builder/) right from GitHub.

But since payload is flattened (https://github.com/slackapi/slack-github-action/blob/main/index.js#L50-L54), it doesn't work.
Can it be configurable?

**Comment by seratch** [comment]
If you are using Incoming Webhooks, please refer to https://github.com/slackapi/slack-github-action/issues/11 -- the issue will be resolved in future versions.

**Comment by stevengill** [comment]
This landed in `v1.16.0`. Going to close the issue, but feel free to re-open if it isn't solved.
