### ISSUE TITLE
Message never gets sent to slack

### ISSUE THREAD

**Issue by ryanbas21** [slackapi/slack-github-action#62]
### Description
I can't rule out that it's me doing something wrong but i've tried this 100 ways it feels like and I can't understand where i'm going wrong.

I've verified that my webhook accepts the payload that is being sent through postman and the message does get posted. 

I've read every line of source code in the repo, and i've determined i'm sending the POST and adding the `time` to the github outputs, and verify that the time is there in my action.

The check itself is green and has no signs that it didn't successfully complete. 

The JSON i'm sending is what my workflow expects (it works if I manually curl/postman).

I've tried all three types of slack integrations, (webhook, workflow, bot). 

I have no idea where the error is, there is no signs of an error. I've run the workflow on ubuntu and macos.

Again, I can manually POST to my webhook url.

I have added it as a secret in my repo/re generated urls/etc

Here is my action:

```
name: Slack Notify
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "author": "${{ github.event.pull_request.user.login }}",
              "title": "${{ github.event.pull_request.title }}",
              "status": "${{ job.status }}",
              "url": "${{ github.event.pull_request.html_url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```

I've compared this to the actions in this repo, the examples, etc.

I follow up this step with

```
      - run: test -n "${{ steps.slack.outputs.time }}"
 ```
 
 Attached is the steps running:
 
<img width="1311" alt="Screen Shot 2022-02-01 at 9 52 52 AM" src="https://user-images.githubusercontent.com/18267769/152013382-79adee89-d6e8-4fa9-b676-9159c10d2d7f.png">

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x ] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version:

node version:

OS version(s):

#### Steps to reproduce:

1. Use above workflow step in a workflow
2. Add a workflow
3. 

#### Expected result:

The post to get sent to slack and post the message 
#### Actual result:

The post seemingly is never sent to slack although the action passes.

**Comment by bognarlaszlo** [comment]
I have this same issue. More strangely yesterday it worked, and today (seemingly) nothing gets sent.

**Comment by andrewlytle** [comment]
Try adding:

```
env:
    SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
```

**Comment by seratch** [comment]
@ryanbas21 Can you double-check if you've set `SLACK_WEBHOOK_URL` in the GitHub repo's secrets?

**Comment by ryanbas21** [comment]
@seratch I have set it, i've also recreated webhook URL's many times. 

@andrewlytle I have tried this also and it still "succeeds" with no message ever sent

**Comment by seratch** [comment]
@ryanbas21 Thanks for sharing the details. Can you set the `SLACK_WEBHOOK_URL` again? Your execution logs show empty in the env part but, if it's correctly set, the output is supposed to be `***`.

Your one:
<img width="600" src="https://user-images.githubusercontent.com/19658/155224064-147e4229-3751-4491-83bc-40f947153551.png">

My one:
<img width="600" src="https://user-images.githubusercontent.com/19658/155224019-5cea51a8-862c-4fdb-8ef6-512f54ea43fe.png">

**Comment by ryanbas21** [comment]
<img width="964" alt="Screen Shot 2022-02-28 at 10 07 24 AM" src="https://user-images.githubusercontent.com/18267769/156026838-849f5596-1996-4e4c-a7de-df9ba5cbb804.png">
Yeah, i've added it (multiple times)
<img width="569" alt="Screen Shot 2022-02-28 at 10 09 18 AM" src="https://user-images.githubusercontent.com/18267769/156026930-6c709077-99c1-40e8-8a29-b089d7df644f.png">
And I am seeing what you are seeing.

**Comment by youngkyo0504** [comment]
@seratch  Thank you😀 I had same problem. finally that way it solved problem.
@ryanbas21 Did you Environment secrets? I solved problem to set Repository secrets!
![image](https://user-images.githubusercontent.com/78121870/156027111-f26a8d86-c903-4d0f-a0ed-bf8a1b24969a.png)

**Comment by ryanbas21** [comment]
This must be my problem, let me do this ☝️

**Comment by ryanbas21** [comment]
My problem is because repository secrets are not shared with pr's made from forks. I have to get the repository owner to make an environment. 

Sorry for the annoying thread, thanks for the help.

**Comment by jtiala** [comment]
If someone is struggling with this and using [reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow), remember that you need to pass secrets from the parent or use `secrets: inherit`.
