### ISSUE TITLE
Action fails silently when the API call fails

### ISSUE THREAD

**Issue by kitchoi** [slackapi/slack-github-action#63]
### Description

There may have been a network issue which causes an API call to fail. However, the workflow did not fail.
The workflow was using Slack Bot Token and a Channel ID while posting a payload.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Reproducible in:

package version: 1.16.0

node version:

OS version(s): Ubuntu 20

#### Steps to reproduce:

1. With a step looking like this
```
  users: slackapi/slack-github-action@v1.16.0
  with:
    channel-id: XXXXX
    payload: {
    "text": "Some text",
    "blocks": [
      {
        "type": "section",
        "text": {
          "type": "mrkdwn",
          "text": "*Some text*"
        }
      }
    ]
  }
  env:
    SLACK_BOT_TOKEN: ***
```
2. Not sure how you could simulate Slack API going down... I am guessing you want this line to raise an exception:
https://github.com/slackapi/slack-github-action/blob/3658c412d46a3dc37a1ec651891c1e64f2981ec8/src/slack-send.js#L66

It is worth noting that the said step runs fine many times, so I am pretty sure that the payload and parameters are set correctly.

#### Expected result:

The step causes the workflow to error

#### Actual result:

The workflow passes.

#### Attachments:

Error logged:
```

(node:2465) UnhandledPromiseRejectionWarning: Error: An API error occurred: fatal_error
    at Object.platformErrorFromResult (/home/runner/work/_actions/slackapi/slack-github-action/v1.16.0/dist/index.js:5082:33)
    at WebClient.apiCall (/home/runner/work/_actions/slackapi/slack-github-action/v1.16.0/dist/index.js:4685:28)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2465) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2465) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by seratch** [comment]
Hi @kitchoi, thanks for taking the time to report this issue. At that timing, the Slack server-side had an incident: https://status.slack.com/2022-02-22 If this GitHub action does not result in failure in the scenario, the error handling should be improved in future versions.

**Comment by kitchoi** [comment]
Thank you @seratch for your prompt response.

In case this helps, I was able to reproduce a similar silent failure by deliberately supplying a channel ID that does not exist:
```
(node:1680) UnhandledPromiseRejectionWarning: Error: An API error occurred: channel_not_found
    at Object.platformErrorFromResult (/home/runner/work/_actions/slackapi/slack-github-action/v1.16.0/dist/index.js:5082:[33](https://github.com/ThoughtRiver/negotiations-cicd/runs/5295133106?check_suite_focus=true#step:7:33))
    at WebClient.apiCall (/home/runner/work/_actions/slackapi/slack-github-action/v1.16.0/dist/index.js:4685:28)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1680) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by seratch** [comment]
Thanks. Yes, I managed to reproduce the issue on my end.

**Comment by zimeg** [comment]
👋 With the [`@2.0.0`](https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0) release we now have [the `errors` input](https://github.com/slackapi/slack-github-action?tab=readme-ov-file#exiting-with-errors) option that can be set to `true` to cause the step to fail if the request fails and the message can't be sent for some reason:

```yaml
- name: Send a message to nowhere
  uses: slackapi/slack-github-action@v2.0.0
  with:
    errors: true
    method: chat.postMessage
    token: ${{ secrets.SLACK_BOT_TOKEN }}
    payload: |
      channel: ""
      text: "Greetings!"
```

This setup will cause the step to fail with the following error:

> SlackError: An API error occurred: channel_not_found

In addition to this, [the `retries` option](https://github.com/slackapi/slack-github-action?tab=readme-ov-file#retrying-failed-requests) might be useful for attempting failed requests multiple times if that's preferred in your workflows:

```yaml
- name: Attempt a burst of requests
  uses: slackapi/slack-github-action@v2.0.0
  with:
    method: chat.postMessage
    retries: RAPID
    token: ${{ secrets.SLACK_BOT_TOKEN }}
    payload: |
      channel: ${{ secrets.SLACK_CHANNEL_ID }}
      text: "Greetings!"
```

I'm hoping these options together might be useful when handling failed API calls 🙏  I'll close this issue for now, but please do feel free to comment with more questions or open another issue whenever!
