### ISSUE TITLE
Action does not error when message could not be sent

### ISSUE THREAD

**Issue by gr2m** [slackapi/slack-github-action#9]
### Description

I'm new to Slack's APIs, and I only installed the action. I missed to install the new app to the channel I want it to send a message to, the PR at #5 would have saved me some time ;)

I wanted to let you know that although the error is logged to the output, the action still exists as if sending the message succeeded. 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version: latest

node version: any

OS version(s): any

#### Steps to reproduce:

1. Create new slack app
2. Install on workspace
3. Without adding the app to a channel, try to send a message to it

#### Expected result:

Action should fail with helpful instructions

#### Actual result:

Error is logged, but exist status is still 0

#### Attachments:

Sorry I've re-ran the action and have no longer access to the run that failed

**Comment by seratch** [comment]
Thanks for the great input. Displaying actionable error messages would be more helpful to developers.

**Comment by zimeg** [comment]
👋 With the [`@2.0.0`](https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0) release we now have [the `errors` input](https://github.com/slackapi/slack-github-action?tab=readme-ov-file#exiting-with-errors) option that can be set to `true` to cause the step to fail if the request fails and the message can't be sent for some reason:

```yaml
- name: Send a message to nowhere
  uses: slackapi/slack-github-action@v2.0.0
  with:
    errors: true
    method: chat.postMessage
    token: ${{ secrets.SLACK_BOT_TOKEN }}
    payload: |
      channel: ""
      text: "Greetings!"
```

This setup will cause the step to fail with the following error:

> SlackError: An API error occurred: channel_not_found

Thanks again for this suggestion too! I'll close this issue, but with excitement to be catching errors a few steps earlier now 🙏 ✨
